### ISSUE TITLE
Suggestion: Better suited HomeKit Control

### ISSUE THREAD

**Issue by vniehues** [dinmammas/homebridge-robonect#11]
Hey! 
I was about to start developing my own plugin for robonect when I stumbled across yours. 
Great work! 

I was planning to use the [FanV2](https://developers.homebridge.io/#/service/Fanv2) as the exposed Service. 
Reason being that it supports the [TargetFanState](https://developers.homebridge.io/#/characteristic/TargetFanState) characteristic.
This could allow the end user to set it to Auto or Manual with a "picker". Auto would be the auto mode and manual could be defined by the user (eod / home / whatever) by selecting the correlating value in the homebridge config.
Start/Stop could then be controlled using the percentage of the ventilator. 
This would prevent the "double auto mode" that you get when you turn both the switch and the fan off. 

Another great option (the better option in my opinion) would be to use the [Outlet Service](https://developers.homebridge.io/#/service/Outlet) and expose "one outlet per mode". 
For the optimal user experience you could then disable every outlet beside the one that was pressed. Essentially making it a remote with a couple of stateful switches. 
As long as you expose 4 or more outlets, they will show as simple on-off buttons in the home app instead of toggle-switches (looks very nice imo).
Using the outlets we would have a cleaner UI, access to all modes and less clutter in the home app.
(Also no "double auto mode")

Again: Great work! Thank your for this plugin :)

**Comment by dinmammas** [comment]
I'll go ahead and close this, and wait for your PR as per #12 :)

**Comment by vniehues** [comment]
Honestly.. don't count on it.. :D 
I'm currently swamped with work. I'll take a look at it when I find the time..
