### ISSUE TITLE
Suggestion: Option to hide switch and only use Fan to toggle Mode

### ISSUE THREAD

**Issue by vniehues** [dinmammas/homebridge-robonect#12]
You could make the modes configurable in the homebridge config. 
"onMode": "Auto",
"offMode": "home"

[possible values](https://forum.robonect.de/viewtopic.php?f=11&t=11): 
- home
- eod
- man
- Auto
- job

**Comment by vniehues** [comment]
Feel free to reach out if you need help with the API-Docs. 
I can translate them for you if need be :)

**Comment by dinmammas** [comment]
Hi! 

Thanks for your suggestion.

The reason behind having both the switch and the fan service operate the mower was that I (I originally intended the plugin to be for me only ;) ) wanted the option to both send the mower home permanently, or end of day.

The most recent update of the fan service allows you to configure the fan service to either start/stop the mower or eod/auto.
For me it makes sense to have the switch being the more 'permanent' on/off switch and the fan for temporary stuffs.

Also if hidden, you'd have no clue if the mower is in auto mode or not. The fan service should only be active when mowing. IMHO.

**Comment by vniehues** [comment]
I think we all start these plugins for ourselves haha :) 

I see where you're coming from and I guess for now this is perfectly fine. Your plugin works perfectly as well so there is little need to change things around.

I'll fork your project and play around with some HomeKit accessories to see if I can build something that better suits my vision. If I'm successful I'll open a PR to discuss these things.

For now I'm going to close this. :)
