### ISSUE TITLE
Problem with Two Mowers

### ISSUE THREAD

**Issue by pillemats** [dinmammas/homebridge-robonect#13]
Hey there

i am using Two mowers with robonect with different ip Adresses and if one is mowing both will shown in hk as mowing! 

Also a Problem is, if „edward“ has an error I get a push note in hk from „Snowball II“

very Strange 

Need some help please how to fix it

Here is my config

        {
            "name": "Edward",
            "mower": "Gardena",
            "model": "Sileno 750",
            "serial-number": "05D40030-36354633-43124252",
            "pollingInterval": 60,
            "fanMode": 0,
            "getUrl": "http://xxx@192.168.178.222:80",
            "accessory": "HomebridgeRobonect"
        },
        {
            "name": "Snowball II",
            "mower": "Gardena",
            "model": "Sileno 750 Smart ",
            "serial-number": "05D80034-39364E4E-43085228",
            "pollingInterval": 60,
            "fanMode": 0,
            "getUrl": "http://xxx@192.168.178.223:80",
            "accessory": "HomebridgeRobonect"
        } 

![EDD6ADD2-3322-437A-BFAD-5DBF4187107C](https://user-images.githubusercontent.com/26164977/177028236-4e393fea-6d04-410c-b7e9-9f0cd9ab0cc5.png)
![FBAA5525-0CD7-4E00-A090-C73CE9B3859D](https://user-images.githubusercontent.com/26164977/177028237-eb2ead04-d306-41f8-bf5f-523f56375d99.jpeg)
![15D1F5FC-B9C1-4DAE-9005-053F5A86D388](https://user-images.githubusercontent.com/26164977/177028238-b3f364a1-70cd-4e7f-b7cb-f91968a578a7.png)

**Comment by dinmammas** [comment]
Checking.

**Comment by dinmammas** [comment]
Just for my information:
Which versions of the plugin and home bridge are you running?

**Comment by dinmammas** [comment]
I've tried and been able to reproduce. And I know what to do to fix it.

While waiting for a fix - please try to set the polling intervals to something odd. 
I set mine to 30s and 37s respectively. This way the won't run at the same time (at least not very often...)

**Comment by pillemats** [comment]
Ok I will try that and waiting for the fix! I am using the newest version of hb and you plugin. Thanks for your support
