### ISSUE TITLE
Feature-Request: optionally remove humidity and temperature sensor

### ISSUE THREAD

**Issue by udochrist** [dinmammas/homebridge-robonect#16]
My Automower / Robonect shows a temperature of 24 degrees and a humidity of 40 % while the true values captured by a weather-sensor are 14 degrees and 90 %. The Robonect Sensor values are so far off that I rather not want to have them in HomeKit at all.

would it be possible to add a toggle so the devices are not created? I‘ve not found a way to remove them in Homebridge or HomeKit once they are published by a device.

**Comment by dinmammas** [comment]
The sensors are only capturing the temp and humidity _inside_ the mower. As it should.

I'll se about adding a toggle to disable the sensors in HomeKit though. :) But it'll be a while.

**Comment by udochrist** [comment]
> The sensors are only capturing the temp and humidity _inside_ the mower. As it should.
> 
> I'll se about adding a toggle to disable the sensors in HomeKit though. :) But it'll be a while.

Then maybe there should be a second device for only the temp and humidity that’s added to HomeKit? As soon as I place my Automower in the room „garden“ then HomeKit shows the Automowers temp as the temperature in the garden. Combined with the weather sensor I see 14-24 degrees then. 
any other ideas are very welcome.

**Comment by dinmammas** [comment]
I keep my mower in a separate room in HomeKit to avoid such data collisions. I name the room Shaun, as that is what the kids have decided that my mower's name is :D

**Comment by udochrist** [comment]
thanks for the update. i‘ll update and test this as soon as it’s released.

**Comment by letsdeal-services** [comment]
Version 1.1.16 is now live.

**Comment by dinmammas** [comment]
Version 1.1.16 is now live.
