### ISSUE TITLE
showHealth seems to be not working

### ISSUE THREAD

**Issue by udochrist** [dinmammas/homebridge-robonect#17]
Hi,
I've updated today to the latest version and added the "showHealth": 0 to the config section.

```       
    {
            "name": "Automower",
            "mower": "Husqvarna",
            "model": "Automower 310",
            "serial-number": "<SERIAL>",
            "pollingInterval": 60,
            "fanMode": 0,
            "showHealth": 0,
            "getUrl": "<URL>",
            "accessory": "HomebridgeRobonect"
        }
```

all restarted o.k. however the temperature and humidity are not gone from the accessories

![Screenshot 2023-09-01 at 18 47 01](https://github.com/dinmammas/homebridge-robonect/assets/869637/1c0c2c9e-3163-4f88-9e0e-dfa6df2d75aa)

any ideas?

reds
Udo

**Comment by dinmammas** [comment]
Config looks OK. Strange tho, as I have had it working since before summer. Give me a day or two to figure it out please.

**Comment by dinmammas** [comment]
Ok, found my mistake. A fix is on the way.

**Comment by udochrist** [comment]
Thanks. as a suggestion: it would be good if the parameter was included in config.schema.json.
then it would be supported by the gui and you wouldn't have to edit manually...

**Comment by udochrist** [comment]
and confirmed. the new value of "2" removes both humidity and temperature from HomeKit.

**Comment by dinmammas** [comment]
> Thanks. as a suggestion: it would be good if the parameter was included in config.schema.json.
> then it would be supported by the gui and you wouldn't have to edit manually...

It is, in this patch release. :)
