### ISSUE TITLE
Gardena Smart System

### ISSUE THREAD

**Issue by danbridgland** [dinmammas/homebridge-robonect#2]
Great work getting the package running.

Does this package use the Gardena Smart System hub?  If so, would it be possible to also support the tap, and moisture sensor accessories and HomeKit sprinkler control?

**Comment by dinmammas** [comment]
Hello and thanks! :)

No, it does not. It connects only to Robonect-cards.

Do you know of an API for the Gardena Smart System? If so, point me there, and I'll see if there's something I can do.

**Comment by danbridgland** [comment]
Thanks for getting back to me.

I’m not sure there’s a public API, but there are similar projects running which may have already uncovered the necessary detail.  Like this https://docs.openhab.org/addons/bindings/gardena/readme.html  and  https://community.openhab.org/t/gardena-smart-system/10961

Hopefully these will give an insight into the Gardena Smart System API.

**Comment by dinmammas** [comment]
Thnx. I'll have a look. 

Although it will be hard to test and troubleshoot without an actual system to work with :)

**Comment by dinmammas** [comment]
Seems someone already have a solution, albeit a bit complex. 

But probably a faster way to get going, than waiting for me to make something out of nothing (as I don't have any equipment to test with).

https://forum.smartapfel.de/forum/thread/1466-gardena-smart-system-sileno-rasenmähroboter-homebridge-plugin-verfügbar/?postID=29647 (In German, Google Translate if you can't read it). See post #4 for details.

**Comment by danbridgland** [comment]
So it seems there are others interested in a Gardena HomeKit solution.  The OpenHAB and HomeKit plug-in option is a little less convenient, I would prefer to keep everything on HomeBridge.

With the Sileno mower you already have, does this operate via the Smart System gateway also?  If so, isn’t this the same system, is it not possible to add the watering features?

**Comment by danbridgland** [comment]
If you have the Samrt Gateway,  I’d be happy to send you a smart sensor, brand new and sealed.

**Comment by dinmammas** [comment]
Nope, I don't. :(

**Comment by danbridgland** [comment]
That is a shame.  Well my offer still stands if you can get a smart gateway.

I’ve emailed Gardena many times asking for HomeKit support, but each time they simple say they will pass my feedback on. :(
