### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by Gophlin** [dinmammas/homebridge-robonect#4]
I'm seeing frequent error messages in my log like the one below:

```
(node:386) UnhandledPromiseRejectionWarning: FetchError: request to http://username:password@10.0.1.130/json?cmd=status failed, reason: connect ECONNRESET 10.0.1.130:80
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-robonect/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:428:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 506)
```

When i browse to the mentioned URL I do see a valid JSON response.

**Comment by Gophlin** [comment]
@dinmammas , could you have a look at this?

**Comment by bsoener** [comment]
Hi. In the winter I unplug my lawn mower and store them in the dry. However, on my homebrigde always comes the error message that the lawn mower is not reachable. Can I turn off this log?

**Comment by dinmammas** [comment]
I will, as soon as my mower starts mowing again.

**Comment by daniestermann** [comment]
Same issue here. Also tried running it as a child bridge.

`homebridge-robonect v1.1.0`
`homebridge v1.3.4`
`node.js v14.15.4`

**Comment by dinmammas** [comment]
Hello!

While I teach myself how to use the fetch library in the correct way, please uninstall the current version of the plugin, and install version 1.0.22 using 
`nom -g install homebridge-robonect@1.0.22`

Sorry for the delay.

**Comment by dinmammas** [comment]
Hi.

I have a beta version if you'd like to try.
npm -g install homebridge-robonect@beta

**Comment by Gophlin** [comment]
Thanks! I just installed it, and I have not seen any errors in the first couple of minutes. Will report back later this week after testing it a bit more.

**Comment by dinmammas** [comment]
The beta is now live, @ version 1.1.2.

I've tested it for several days agains a few different mowers, no errors.

I'll close this now, please reopen if needed.
