### ISSUE TITLE
Error log: This plugin slows down Homebridge.

### ISSUE THREAD

**Issue by bsoener** [dinmammas/homebridge-robonect#5]
Is the plugin no longer being developed? When I upgrade my Homebridge to the latest version I get this error message:

This plugin slows down Homebridge.

**Comment by dinmammas** [comment]
It is, tho I'm doing it as a hobby, and mostly during the summer when my mower is active.

The nature of Robonect itself makes the plugin run slowly, as one of the base calls requires it to wake the mower up.
I've added a switch which will be released soon, that gives the option to remove this call from the plugin.

**Comment by dinmammas** [comment]
Hello!

While I teach myself how to use the fetch library in the correct way, please uninstall the current version of the plugin, and install version 1.0.22 using 
`nom -g install homebridge-robonect@1.0.22`

Sorry for the delay.

**Comment by dinmammas** [comment]
Hi!
I have a beta version if you'd like to try.
npm -g install homebridge-robonect@beta

**Comment by dinmammas** [comment]
The beta is now live, @ version 1.1.2.

I've tested it for several days agains a few different mowers, no errors.

I'll close this now, please reopen if needed.
