### ISSUE TITLE
Lawn mower does not start

### ISSUE THREAD

**Issue by bsoener** [dinmammas/homebridge-robonect#8]
Hello dinmammas,

as soon as I want to start at the Homekit, the mower does not respond. Must then start it via the Gardena app. But strangely enough I can send while the mower is running via the Homekit back to the base? Do you have any idea what this can be?

**Comment by dinmammas** [comment]
Hello! Which accessory are you trying to start the mower with?

The fan only works if mower is in auto mode.

**Comment by bsoener** [comment]
I start my mower via Homekit Iphone. Since I did not get any response, I had to start it via Gardena Gateway App. But when I stop it via Homekit and send it back to the base, it works. My mower already has a Robonect HX installed for info.

**Comment by dinmammas** [comment]
Hi!

No, what I was asking was if you're using the switch accessory or the fan accessory when you want to 'start' the mower?

Setting the switch accessory to 'on' sets the mower in auto mode. However it needs to be within its set timer interval to actually start to mow. 

The fan accessory only works if the switch accessory is 'on' and the mower is mowing.

**Comment by bsoener** [comment]
so only the switch for on has already been activated. Unfortunately no reaction. There was a software update for the Robonect HX (Robonect® Hx V1.3). Can it possibly be due to the fact that something was changed?

**Comment by bsoener** [comment]
Got it out. The update of HX has changed the timers. Thanks for your help anyway.
