### ISSUE TITLE
Feature request: add Sensor that gets triggered in case of issues

### ISSUE THREAD

**Issue by udochrist** [dinmammas/homebridge-robonect#9]
It would be great to get a notification in HomeKit when the mower is out of the area or stuck/lifted from the ground. 

i think a simple sensor in HomeKit that gets set to on in this error-conditions should be enough to trigger a message on the phone/watch.

**Comment by dinmammas** [comment]
Thanks for the suggestion - I will check it out.

**Comment by Geoff-Hz** [comment]
Hello,
In my case, it can be nice if it’s possible to add sensor when mowing is starting and stopping. 
like this, I can have notifications from HomeKit. 
or
When is on auto mode or off. 
the deal is to know when he can mower 
Thanks

**Comment by dinmammas** [comment]
Hello @Geoff-Hz 
I think I'll limit myself to error notifications as of now.
As it is, I'm not able to change the way that the notifications look or what text/information they can contain.

I suggest maybe that you use the built-in functionality in Robonect, such as mqtt or push service, to get messages for mowing/returning home. 

Best,
David

**Comment by dinmammas** [comment]
@udochrist Just checking in - motion sensor is now in testing :)

**Comment by udochrist** [comment]
> Just checking in - motion sensor is now in testing :)

I'm using the plugin in an oznzu homebridde docker container. do you know of any easy possibility to switch to that testing version using such homebridge containers?
